# Ultralytics YOLO ?, GPL-3.0 license
# Modified by Diego Augusto Silva to include ReYOLOv8 training and prediction parameters 

task: detect  # inference task, i.e. detect, segment, classify
mode: train   # YOLO mode, i.e. train, val, predict, export

# Train settings -------------------------------------------------------------------------------------------------------
model:          # path to model file, i.e. yolov8n.pt, yolov8n.yaml
data:           # path to data file, i.e. coco128.yaml
epochs: 100     # number of epochs to train for
patience: 50    # epochs to wait for no observable improvement (early stopping)
batch: 16       # number of images per batch (-1 for AutoBatch)
save: True      # save train checkpoints and predict results
save_period: -1 # save checkpoint every x epochs (disabled if < 1)
cache: False    # True/ram, disk or False (data loading cache)
device:         # cuda device id(s) or cpu
workers: 8      # number of dataloader workers
project:        # project name
name:           # experiment name
exist_ok: False # whether to overwrite existing experiment
pretrained: False  # whether to use a pretrained model
optimizer: SGD     # choices: SGD, Adam, AdamW, RMSProp
verbose: True
seed: 0
deterministic: True
min_memory: False

# Val/Test settings ----------------------------------------------------------------------------------------------------
val: True        # run validation during training
split: val       # 'val', 'test', or 'train'
save_json: False
save_hybrid: False
conf:            # confidence threshold (set in predict; low for val)
iou: 0.7         # IoU threshold for NMS
max_det: 300
half: False
dnn: False
plots: True

# Prediction settings --------------------------------------------------------------------------------------------------
source:          # source path for images or videos
show: False
save_txt: False
save_conf: False
save_crop: False
hide_labels: False
hide_conf: False
line_thickness: 3
visualize: False
classes:         # filter by class ids
boxes: True

# Export settings ------------------------------------------------------------------------------------------------------
format: torchscript
keras: False
optimize: False
int8: False
dynamic: False
simplify: False
opset:
workspace: 4
nms: False

# Hyperparameters ------------------------------------------------------------------------------------------------------
lr0: 0.01        # initial learning rate
lrf: 0.01        # final lr multiplier
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
warmup_bias_lr: 0.1
box: 7.5
cls: 0.5
dfl: 1.5
fl_gamma: 0.0
nbs: 64
invert: 0.0
suppress: 0.0
flip: 0.0
positive: 0.0
zoom_out: 0.0
max_zoom_out_factor: 1.2
min_zoom_out_factor: 1.0

############ Video Settings --------------------------------------------------------------------------------------------
clip_length: 5
clip_stride: 5
channels: 10

#### Other settings ----------------------------------------------------------------------------------------------------
rect: True
cos_lr: False
imgsz: 320
val_epoch: 1
resume: False
speed: False
zero_hidden: False

# Custom config.yaml ---------------------------------------------------------------------------------------------------
cfg:

